### ISSUE TITLE
Allow the user to decrease the default value for total code cache

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9-docs#138]
**Issue or pull request number:**
*https://github.com/eclipse/openj9/pull/3446*

**Overview:**
*Previously, the user could only increase the default value of the total code cache with the option -Xcodecachetotal. The PR mentioned above allows the user to also decrease the total size of the code cache. However, a minimum limit of 2MB is imposed.*

**Applies to the following JDK versions:**
*Java 8 and later*

**Applies to the following platforms:**
*All platforms*

**Comment by pshipton** [comment]
There is no indication at https://www.eclipse.org/openj9/docs/xcodecachetotal/ the change occurs from the 0.12 release.

**Comment by SueChaplain** [comment]
> There is no indication at https://www.eclipse.org/openj9/docs/xcodecachetotal/ the change occurs from the 0.12 release.

That's correct. The documentation is up to date with the code base and has no revision markup. What changes per release is captured in the Release notes for that release. E.g. https://www.eclipse.org/openj9/docs/version0.12/ ..... none of the changes implemented since 0.8.0 are captured in the body of the document.

Note: We have work planned to build and provide a downloadable zip of content for each release, with the last release being available on the Eclipse site (draft on ghpages) ... yet to be implemented.
