### ISSUE TITLE
Enable bootstrap class sharing by default jdk8

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-docs#149]
**Issue or pull request number:**
https://github.com/eclipse/openj9/pull/3858

**Overview:**
See #103 and #110. This adds the same changes for jdk8.

**Applies to the following JDK versions:**
jdk8

**Applies to the following platforms:**
#103 applies to all jdk8 platforms.
#110 affects all jdk8 platforms but osx

**Comment by pshipton** [comment]
Re the previous comment, I have updated the description to include this.

**Comment by doveye** [comment]
The draft doc changes are on an internal server (temporary until we get infrastructure in place at Eclipse to enable multiple simultaneous drafts - work in progress) - please take a look and comment if modifications are required:
- https://pages.github.ibm.com/runtimes/openj9-docs-staging/166/shrc/ - "Enabling class data sharing" section - I removed the Java 8/11 icons and made the old content specific to macOS only. (For comparison, live docs are at https://www.eclipse.org/openj9/docs/shrc/)
- https://pages.github.ibm.com/runtimes/openj9-docs-staging/166/xshareclasses/#cachedir - In the "On Aix..." bullet, I removed the Java 8/11 icons, and merged the content so that mention of the old dir is only for when the groupAccess param is specific. (For comparison, live docs are at https://www.eclipse.org/openj9/docs/xshareclasses/#cachedir)

**Comment by hangshao0** [comment]
FYI: This PR will enable bootstrap class sharing by default on OSX (on Java 8 and Java 11+): https://github.com/eclipse/openj9/pull/4079.

**Comment by doveye** [comment]
I see the PR for macOS has been merged, so I've updated the docs again to remove the macOS-specific content. Draft docs now at:
https://pages.github.ibm.com/runtimes/openj9-docs-staging/174/shrc/
https://pages.github.ibm.com/runtimes/openj9-docs-staging/174/xshareclasses/#cachedir  (I assume the cacheDir on macOS is the same as other non-Windows platforms)

**Comment by doveye** [comment]
Great, think this can be closed now, thanks Hang.
