### ISSUE TITLE
Enhancement to report any unrecognized options that begin with "-XX:

### ISSUE THREAD

**Issue by AidanHa** [eclipse/openj9-docs#212]
[eclipse/openj9#4435](https://github.com/eclipse/openj9/pull/4435)

**Overview:**
Give user options to to report any unrecognized options that begin with "-XX:"

Applies to all JDK version

Applies to all platforms

-XX:-IgnoreUnrecognizedXXColonOptions will report any unrecognized "-XX:" options
-XX:+IgnoreUnrecognizedXXColonOptions will ignore any unrecognized "-XX:" options. This option is set by default.

**Comment by AidanHa** [comment]
note the change in the command line option

**Comment by doveye** [comment]
Hi @AidanHa. I've made the doc updates, can you please check and let me know if anything needs to be changed:

- There is a section in the draft [What's New](https://eclipse.github.io/openj9-docs-staging/236/version0.14/) topic for release 0.14.0. That links to...
- [New topic](https://eclipse.github.io/openj9-docs-staging/236/xxignoreunrecognizedxxcolonoptions/) for the new option
- I've also updated [New to OpenJ9](https://eclipse.github.io/openj9-docs-staging/236/openj9_newuser/) and [Using -XX command-line options](https://eclipse.github.io/openj9-docs-staging/236/xx_jvm_commands/), because they talked about unrecognized options being ignored

Thanks :)

**Comment by pshipton** [comment]
In the What's New, there are backslashes in `-XX:\[+|-\]IgnoreUnrecognizedXXColonOptions.`.
Otherwise lgtm

**Comment by doveye** [comment]
Good old copy and paste! Thanks Peter, now fixed.

**Comment by AidanHa** [comment]
lgtm! I think we can close this Issue now :)

**Comment by doveye** [comment]
Excellent, thanks Aidan
