### ISSUE TITLE
Minor formatting issues with Concurrent Scavenge note about Z

### ISSUE THREAD

**Issue by joransiu** [eclipse/openj9-docs#292]
**Page containing the error:**

https://www.eclipse.org/openj9/docs/xgc/#concurrentscavenge

*www.eclipse.org/openj9/docs/*

**Describe the error and the update needed:**

Two minor issues with the the embedded content titled "Note: Linux on Z and z/OS":

1.  `IBM z14&trade;`  <-- the trademark symbol isn't expanded properly.

2.  `<i class="fa fa-pencil-square-o" aria-hidden="true"></i> ` HTML text is actually visible in the last line...

**Comment by SueChaplain** [comment]
Good spot @joransiu - likely caused when we have to quickly back out some 0.15 changes due to the 0.14.2 release. The changes we backed out are now back in our current draft docs, and the formatting is ok: https://eclipse.github.io/openj9-docs/xgc/#concurrentscavenge.

This problem will fix itself when we publish 0.15, which is only just around the corner. Since the current docs are readable (if not ideal), I propose we wait for 0.15?

**Comment by joransiu** [comment]
Waiting for 0.15 sounds reasonable.  Thanks @SueChaplain!
