### ISSUE TITLE
Document how to create a smaller jlinked image when translations not required

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-docs#308]
When jlinking an image, if translations for non-English languages are not required, the translation files can be removed. 

https://github.com/eclipse/openj9/issues/4488#issuecomment-496279476

We should find a place to document this tip.

**Comment by SueChaplain** [comment]
I've been trying to think about where to put this in the current doc set so that it can be easily found.

One idea: There is an issue on the website to move the build instructions into the user doc. If we did this, would it make sense to include `jlink` as another mechanism for creating a runtime image?

 Any other thoughts.
BTW - although we need to get this done, I am not prioritising it for 0.15.0 unless we have an easy solution.

**Comment by pshipton** [comment]
How about adding a jlink section under Tools? We shouldn't document jlink itself, but can add the tips about using jlink with OpenJ9 there.

**Comment by SueChaplain** [comment]
Tools has just moved into the Diagnostics section, so not sure that's appropriate. However, we could have a section in Getting Started -> Runtime Options -> Using Jlink?

**Comment by SueChaplain** [comment]
Took a chance on Getting started being appropriate and created https://github.com/eclipse/openj9-docs/pull/318
