### ISSUE TITLE
Supported environments minimum OS levels

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-docs#41]
https://www.eclipse.org/openj9/docs/openj9_support/index.html indicates Ubuntu 14 (glibc 2.19) for Java 8 and Ubuntu 16 (glibc 2.23) for Java 9 and later are the minimum OS environments. Although the OpenJ9 project might be using these levels for testing since they are the available machines, they are not the minimum levels intended.

Going via the glibc levels, the following are the minimum OSes.

xLinux, zLinux should be CentOS 6 (glibc 2.12)
pLinux (LE) should be CentOS 7 (glibc 2.17)

**Comment by pshipton** [comment]
@DanHeidinga @mstoodle are you good with this?

**Comment by DanHeidinga** [comment]
+ 1

**Comment by SueChaplain** [comment]
@pshipton I'm not quite sure how you want this change implemented.

- Do I switch out Ubuntu in all the tables for CentOS? Is that what you intend? 
- Do you want the glibc level in the table too? 
- Should I amend the sentence that talks about Linux kernel versions to refer to glibc instead somehow? 

I'm wondering how user friendly this support statement is. For anyone building OpenJDK, it probably makes sense. For someone who just wants to use a runtime and is wondering whether their OS is ok, would it be better to stick with a list of common Linux distros and levels as we do for the SDK docs?

**Comment by pshipton** [comment]
> Do I switch out Ubuntu in all the tables for CentOS? Is that what you intend?

Yes

> Do you want the glibc level in the table too?

I could be added in brackets after the OS

> Should I amend the sentence that talks about Linux kernel versions to refer to glibc instead somehow?

Where did the kernel information originate from? (CentOS6 has a 2.6 kernel version, and 7 is 3.1)

> would it be better to stick with a list of common Linux distros and levels

That is fine with me.

**Comment by SueChaplain** [comment]
The kernel information came from a longish discussion I had with Mark trying to understand what these build tables represented as support statements (my mindset being more user-oriented than compiler-oriented). IIRC, once I had understood that, I figured out the kernel level for the Ubuntu versions we were showing and then added the statements for people to determine whether other distros would be supported. 

Since the current tables will be well understood by OpenJDK developers, lets leave them in place, but maybe we can add some common Linux distros and levels for end user who just wants to know "will it work for me?"

Ubuntu, RHEL, SLES ??

@mstoodle - are you ok with all this. This topic was based on your statement, so want to make sure you're comfortable with the proposal to add a short list of Linux distros and levels that we support.

**Comment by pshipton** [comment]
If a distro has a glibc level which is >= to the minimum level then it should work. Although I suppose there may be other factors to consider. Ubuntu, RHEL, SLES should all work according to the minimum glibc levels.

**Comment by mstoodle** [comment]
I support this change, but I would also prefer to add to the list of platforms rather than only specify the minimum. For example, someone comfortable using Ubuntu probably wouldn't interpret "CentOS 6" as obviously implying they're ok to use Ubuntu.

We should probably also highlight the platforms that the project itself uses to build and test.

**Comment by SueChaplain** [comment]
Is it going to be problematic listing distros that have glibc >= 2.12? (x&z) I just started trying to build a list and Ubuntu 12.04 is glibc 2.15 and SLES 9 is 2.3.3. Those are awfully old - do we really want to list them?

**Comment by pshipton** [comment]
> Those are awfully old - do we really want to list them?

Not really. We can limit support to OSes which are still supported, and will continue to be supported. CentOS/RHEL 6/7, SLES 12, and Ubuntu 16/8 is my suggestion. With a disclaimer that we don't test all these platforms, we just expect them to work. Not that OpenJ9 promises any support, but support for OS specific issues is limited to OS availability and lifetimes.

**Comment by pshipton** [comment]
> should we change our build environment table to show Ubuntu 16.04 (which I think is what it is at Adopt)

yes I think we should.

There aren't any builds for Power BE at OpenJ9 or Adopt, I don't think it should be listed as supported. It is an IBM platform for Java 8 and the OpenJ9 code to support this will be maintained by IBM, but this doesn't mean OpenJ9 builds will work. If somebody really wants support at OpenJ9 then it could be added later, although we'd need to find machines.
