### ISSUE TITLE
Document 't' and 'T' suffixes for -X options that take a size parameter

### ISSUE THREAD

**Issue by avermeer** [eclipse/openj9-docs#429]
**Issue or pull request number:**
https://github.com/eclipse/openj9/issues/7427

**Overview:**
There is a need to update [Using -X command-line options](https://www.eclipse.org/openj9/docs/x_jvm_commands/) and [Using -XX command-line options](https://www.eclipse.org/openj9/docs/xx_jvm_commands/) pages in order to reflect the added support for 't' and 'T' suffixes for `-X` and `-XX` options that take a <size> parameter through the pull requested associated to issue [#7427](https://github.com/eclipse/openj9/issues/7427).

The documentation change should take into account the limitation that 't' and 'T' suffixes are only supported on 64-bit versions of OpenJ9 VM.

**Release target:**
Eclipse OpenJ9 0.18.0

**Applies to the following JDK versions:**
8 and later

**Applies to the following platforms:**
All platforms

**Comment by SueChaplain** [comment]
Hi @avermeer - thank you for your contribution.

I believe the release target for this change must be 0.18.0, because 0.17.0 has already been released and your changes at OpenJ9 seem to be open still. No problem here.

I see you have created a PR already. In addition to the 2 files you have updated, we would also need an entry in the version0.18.md release notes file to explain that this is new in this release.
You can look at other changes in that file to see what is required (bullet item with a link to the section where the change is detailed)

Is this really supported only on 64-bit systems?

**Comment by avermeer** [comment]
Hi @SueChaplain, thank you very much for your feedbacks on my first contribution to OpenJ9 documentation.

I agree that I have made a mistake on the targeted release.
I will redo a PR with this fix and an entry in version0.18.md release notes.

Last, I confirm that this is only supported on 64-bit systems : 32-bit HotSpot-based Java versions do not have this option, so this change is consistent.

**Comment by avermeer** [comment]
Please wait until merging this PR : finally I was asked to add 't' / 'T' suffix support in 32-bit mode as well - even if that leads to out of bounds errors in 32-bits.

I'll push some commits about it tomorrow...

**Comment by pshipton** [comment]
Added `WIP` to the title, which means Work in Progress, do not merge.

**Comment by avermeer** [comment]
Commit of removal of 64-bit only restriction.
