### ISSUE TITLE
JEP 343 : Packaging Tool - supported platforms

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9-docs#474]
**Subject:**
The supported platforms of `OpenJ9 JEP 343` are `Linux`, `macOS` and `Windows`. This is also stated in the JEP doc [1].
More specifically, `AIX` and `zOS` are not supported.

@SueChaplain could you advise the doc location for this limitation?

fyi @DanHeidinga

[1] https://openjdk.java.net/jeps/343

**Comment by SueChaplain** [comment]
I would put this limitation in the release notes that live in the OpenJ9 repo. If others believe it should also be in the user docs, we can find a home for it there too.

**Comment by DanHeidinga** [comment]
@SueChaplain Would we normally add documentation for something like the `jpackager` tool where there is nothing OpenJ9-specific about it?  If so, the platform limitations should live in the same place

**Comment by SueChaplain** [comment]
@DanHeidinga - the user docs don't normally cover things that are not specific to OpenJ9, but in this case, we ought to mention the platform support differences somewhere. AdoptOpenJDK do have release notes, so maybe we can request something there as they have OpenJ9 and HotSpot builds for AIX. However, since 0.19.0 is all about OpenJDK 14, and this JEP is introduced here, we could also add a small mention in the release topic about jpackage not providing any package formats for AIX or z/OS. (I guess there is no interest in extending this JEP to include anything like installp or SPM/E either?!)

**Comment by DanHeidinga** [comment]
> However, since 0.19.0 is all about OpenJDK 14, and this JEP is introduced here, we could also add a small mention in the release topic about jpackage not providing any package formats for AIX or z/OS.

+1 to a small mention in the release topic.

> (I guess there is no interest in extending this JEP to include anything like installp or SPM/E either?!)

It will depend on adoption of the jpackage tool and the demand from users.  We're open to extending this in the future
