### ISSUE TITLE
Add examples of how to specify methods to `-Xaot:exclude=<method>`

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9-docs#566]
I am thinking the best way to avoid this bug is to just exclude AOT for the problematic method. I see there is an option `-Xaot:exclude=<method>` in https://www.eclipse.org/openj9/docs/xaot/, but there's no mention as to what the correct syntax for specifying the method is. What should I put as method?

- `akka/stream/impl/GraphStageIsland.onIslandReady()V`
- `akka/stream/impl/GraphStageIsland.onIslandReady()`
- `akka/stream/impl/GraphStageIsland.onIslandReady`
- `akka.stream.impl.GraphStageIsland.onIslandReady`

It would be nice to document that somewhere

_Originally posted by @edrevo in https://github.com/eclipse/openj9/issues/9600#issuecomment-631305546_

**Comment by pmhayward** [comment]
@DanHeidinga @dsouzai @andrewcraik @cathyzhyi 
Some help needed, please!
Before I add an (incorrect) example, what _is_ the correct syntax? [#9600](https://github.com/eclipse/openj9/issues/9600#issuecomment-631305546) doesn't quite get there other than by moving the problem to a different `-Xaot` option with this syntax: 
`-Xaot:loadExclude={akka/stream/impl/GraphStageIsland.onIslandReady*}`

- Does that, more generally, equate to `-Xaot:loadExclude={<package>/<Class>.<method>*}` ?
- Are all those parts required?
- Are the braces `{...}` always needed, or just in this example (not currently in docs)?
- Is it the same syntax for `-Xaot:exclude`, `-Xaot:loadExclude`, and `-Xaot:loadLimit`?
- When is  the `*` needed re these three options? Can any of them specify a method _prefix_ by using a wildcard (not what's currently implied in docs)?

**Comment by dsouzai** [comment]
The syntax is `-Xaot:exclude{<regularExpression>}`. 

<hr/>

> Does that, more generally, equate to -Xaot:loadExclude={<package>/<Class>.<method>*} ?
>
> When is the * needed re these three options? Can any of them specify a method prefix by using a wildcard (not what's currently implied in docs)?

Strictly speaking, if you have the exact method name, you don't need a `*`. To use @DanHeidinga 's example above, if the method's full signature is `akka/stream/impl/GraphStageIsland.onIslandReady()V`
then
```
-Xaot:exclude={akka/stream/impl/GraphStageIsland.onIslandReady()V}
```
will exclude the method. However, if you only put
```
-Xaot:exclude={akka/stream/impl/GraphStageIsland.onIslandReady()}
```
it will not match the method. However
```
-Xaot:exclude={akka/stream/impl/GraphStageIsland.onIslandReady()*}
```
will match; it will also match, for example, `akka/stream/impl/GraphStageIsland.onIslandReady()I`

<hr/>

> Are all those parts required?

No, however; the less parts you have, the more general the filter becomes (assuming you've added `*` appropriately).

<hr/>

> Are the braces {...} always needed, or just in this example (not currently in docs)?

Yes, if you want to exclude everything, for example, you'd have to do
```
-Xaot:exclude={*}`
```

<hr/>

> Is it the same syntax for -Xaot:exclude, -Xaot:loadExclude, and -Xaot:loadLimit?

yeah, same syntax

<hr/>

There's an important subtlety to note:

`exclude`, `limit`, `limitFile` have the same behaviour regardless of whether they're specified on `-Xjit` or `-Xaot`. That is, they filter what the compiler is allowed to compile (AOT or otherwise). Consequence: if you specify `-Xaot:exclude={...}`, it will also prevent a JIT compilation and those methods will always be interpreted.

`loadExclude`, `loadLimit`, `loadLimitFile` must only be specified on `-Xaot`. This will filter what AOT code the compiler is allowed to load from the SCC. The consequence is that the compiler will then do a JIT compilation instead.

**Comment by dsouzai** [comment]
In the staging doc you said that `count`, `exclude`, `limit`, `limitFile` are for "Compile and load". That's not true, it's only true for Compile. You can think of the JIT having 3 "modes" of compilation:

1. JIT Compilation
2. AOT Compilation
3. AOT Load

1 and 2 are essentially the same, except that in 1 we store the body into the Code Cache in RAM, and in 2 we store the body into the SCC on disk. 3 is when the JIT copies the compiled body from the SCC on disk into the Code Cache in RAM and relocates it.

`exclude`, `limit`, `limitFile`  applies to BOTH 1 and 2 regardless of whether you specify it on `-Xjit` or `-Xaot`.

`loadExclude`, `loadLimit`, `loadLimitFile` applies to ONLY to 3, and must only be specified on `-Xaot`.

`count` will apply to 1 if specified on `-Xjit` and 2 if specified on `-Xaot`.


> I'm still a bit confused about the use of braces {...} in the parameters.

The braces are part of the syntax.

**Comment by pmhayward** [comment]
@dsouzai ... thanks for your help. I fixed those few things you mentioned before closing this issue.
