### ISSUE TITLE
Discussion of XX:MaxDirectMemorySize option incorrectly refers to "heap memory"

### ISSUE THREAD

**Issue by gjdeval** [eclipse/openj9-docs#947]
[**Page containing the error:**](https://www.eclipse.org/openj9/docs/xxmaxdirectmemorysize/)

*www.eclipse.org/openj9/docs/*

> ... limits heap memory used for Direct Byte Buffers to ...

The references to "heap memory" in the description are incorrect. DBBs are stored in native memory, though a small reference object to access them is located on the heap ... but the limit is on the native memory consumption, not the heap memory used.

**Comment by Sreekala-Gopakumar** [comment]
@gjdeval, 

Changed "By default, the VM limits the amount of heap memory used for Direct Byte Buffers to 87.5% of the maximum heap size." to "By default, the VM limits the amount of native memory used for Direct Byte Buffers to 87.5% of the maximum heap size."

Also, changed the next line "By default, the class library limits the amount of heap memory used for Direct Byte Buffers to the same value as the maximum heap size." to "By default, the class library limits the amount of native memory used for Direct Byte Buffers to the same value as the maximum heap size."

In the above line, need a clarification. Should "By default, the class library limits..." be changed to "By default, the VM limits..."

Please provide your review comments so that I can finalise this change.

Thanks!

**Comment by gjdeval** [comment]
Thanks for the changes from "heap memory" to "native memory" - those are correct.

I do not know the answer to your question about whether "VM" or "class library" is the controlling factor ... maybe @pshipton or @amicic  can clarify that point.

**Comment by pshipton** [comment]
Do we really need to specify? It's the class library that imposes the limitation.

**Comment by gjdeval** [comment]
Probably it is just a question of how to phrase the statement, I agree that the particular enforcement mechanism is not crucial for this level of doc ... could go with passive voice I suppose:

"By default, the amount of native memory used for Direct Byte Buffers is limited to 87.5% of the maximum heap size."
and
"By default, the amount of native memory used for Direct Byte Buffers is limited to the maximum heap size."

**Comment by Sreekala-Gopakumar** [comment]
Updated the document as per the review comments.

**Comment by Sreekala-Gopakumar** [comment]
@pshipton, @gjdeval Could you please confirm that the changes are fine? If they are fine, then we can merge the change and close this issue.

**Comment by pshipton** [comment]
You can also see the live changes at the following
https://eclipse-openj9.github.io/openj9-docs-staging/955/xxmaxdirectmemorysize/

The Pull Request where you can make review comments is https://github.com/eclipse-openj9/openj9-docs/pull/955

**Comment by pshipton** [comment]
The previous link (to https://github.com/Sreekala-Gopakumar/openj9-docs/commit/86c7b88c01821dd3fcb1ae2330542e7637a80518) obsolete, the actual changes are seen here
https://github.com/eclipse-openj9/openj9-docs/pull/955/files

**Comment by gjdeval** [comment]
Thanks, looks good to me.
